/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _authenticatedSubjectsRouteImport } from './routes/__authenticated/subjects'
import { Route as _authenticatedProgressRouteImport } from './routes/__authenticated/progress'
import { Route as _authenticatedDashboardRouteImport } from './routes/__authenticated/dashboard'
import { Route as _authenticatedSubjectSubjectIdRouteImport } from './routes/__authenticated/subject.$subjectId'
import { Route as _authenticatedLessonLessonIdRouteImport } from './routes/__authenticated/lesson.$lessonId'
import { Route as _authenticatedLessonLessonIdQuizRouteImport } from './routes/__authenticated/lesson.$lessonId.quiz'
import { Route as _authenticatedLessonLessonIdIndexRouteImport } from './routes/__authenticated/lesson.$lessonId.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedSubjectsRoute = _authenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedProgressRoute = _authenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedDashboardRoute = _authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedSubjectSubjectIdRoute =
  _authenticatedSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedLessonLessonIdRoute =
  _authenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedLessonLessonIdIndexRoute =
  _authenticatedLessonLessonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authenticatedLessonLessonIdRoute,
  } as any)
const _authenticatedLessonLessonIdQuizRoute =
  _authenticatedLessonLessonIdQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => _authenticatedLessonLessonIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof _authenticatedDashboardRoute
  '/progress': typeof _authenticatedProgressRoute
  '/subjects': typeof _authenticatedSubjectsRoute
  '/lesson/$lessonId': typeof _authenticatedLessonLessonIdIndexRoute
  '/subject/$subjectId': typeof _authenticatedSubjectSubjectIdRoute
  '/lesson/$lessonId/quiz': typeof _authenticatedLessonLessonIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof _authenticatedDashboardRoute
  '/progress': typeof _authenticatedProgressRoute
  '/subjects': typeof _authenticatedSubjectsRoute
  '/lesson/$lessonId': typeof _authenticatedLessonLessonIdIndexRoute
  '/subject/$subjectId': typeof _authenticatedSubjectSubjectIdRoute
  '/lesson/$lessonId/quiz': typeof _authenticatedLessonLessonIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/__authenticated/dashboard': typeof _authenticatedDashboardRoute
  '/__authenticated/progress': typeof _authenticatedProgressRoute
  '/__authenticated/subjects': typeof _authenticatedSubjectsRoute
  '/__authenticated/lesson/$lessonId': typeof _authenticatedLessonLessonIdRouteWithChildren
  '/__authenticated/subject/$subjectId': typeof _authenticatedSubjectSubjectIdRoute
  '/__authenticated/lesson/$lessonId/': typeof _authenticatedLessonLessonIdIndexRoute
  '/__authenticated/lesson/$lessonId/quiz': typeof _authenticatedLessonLessonIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/progress'
    | '/subjects'
    | '/lesson/$lessonId'
    | '/subject/$subjectId'
    | '/lesson/$lessonId/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/progress'
    | '/subjects'
    | '/lesson/$lessonId'
    | '/subject/$subjectId'
    | '/lesson/$lessonId/quiz'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/admin'
    | '/login'
    | '/signup'
    | '/__authenticated/dashboard'
    | '/__authenticated/progress'
    | '/__authenticated/subjects'
    | '/__authenticated/lesson/$lessonId'
    | '/__authenticated/subject/$subjectId'
    | '/__authenticated/lesson/$lessonId/'
    | '/__authenticated/lesson/$lessonId/quiz'
  fileRoutesById: FileRouteTypes['fileRoutesById']
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/subjects': {
      id: '/__authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof _authenticatedSubjectsRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/progress': {
      id: '/__authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof _authenticatedProgressRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/dashboard': {
      id: '/__authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _authenticatedDashboardRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/subject/$subjectId': {
      id: '/__authenticated/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof _authenticatedSubjectSubjectIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/lesson/$lessonId': {
      id: '/__authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof _authenticatedLessonLessonIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/lesson/$lessonId/': {
      id: '/__authenticated/lesson/$lessonId/'
      path: '/'
      fullPath: '/lesson/$lessonId/'
      preLoaderRoute: typeof _authenticatedLessonLessonIdIndexRouteImport
      parentRoute: typeof _authenticatedLessonLessonIdRoute
    }
    '/__authenticated/lesson/$lessonId/quiz': {
      id: '/__authenticated/lesson/$lessonId/quiz'
      path: '/quiz'
      fullPath: '/lesson/$lessonId/quiz'
      preLoaderRoute: typeof _authenticatedLessonLessonIdQuizRouteImport
      parentRoute: typeof _authenticatedLessonLessonIdRoute
    }
  }
}

interface _authenticatedLessonLessonIdRouteChildren {
  _authenticatedLessonLessonIdIndexRoute: typeof _authenticatedLessonLessonIdIndexRoute
  _authenticatedLessonLessonIdQuizRoute: typeof _authenticatedLessonLessonIdQuizRoute
}

const _authenticatedLessonLessonIdRouteChildren: _authenticatedLessonLessonIdRouteChildren =
  {
    _authenticatedLessonLessonIdIndexRoute:
      _authenticatedLessonLessonIdIndexRoute,
    _authenticatedLessonLessonIdQuizRoute:
      _authenticatedLessonLessonIdQuizRoute,
  }

const _authenticatedLessonLessonIdRouteWithChildren =
  _authenticatedLessonLessonIdRoute._addFileChildren(
    _authenticatedLessonLessonIdRouteChildren,
  )

interface _authenticatedRouteChildren {
  _authenticatedDashboardRoute: typeof _authenticatedDashboardRoute
  _authenticatedProgressRoute: typeof _authenticatedProgressRoute
  _authenticatedSubjectsRoute: typeof _authenticatedSubjectsRoute
  _authenticatedLessonLessonIdRoute: typeof _authenticatedLessonLessonIdRouteWithChildren
  _authenticatedSubjectSubjectIdRoute: typeof _authenticatedSubjectSubjectIdRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedDashboardRoute: _authenticatedDashboardRoute,
  _authenticatedProgressRoute: _authenticatedProgressRoute,
  _authenticatedSubjectsRoute: _authenticatedSubjectsRoute,
  _authenticatedLessonLessonIdRoute:
    _authenticatedLessonLessonIdRouteWithChildren,
  _authenticatedSubjectSubjectIdRoute: _authenticatedSubjectSubjectIdRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authenticatedRoute: _authenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
